### ISSUE TITLE
Update get_email_passkey function in glassdoor_scrapper.py

### ISSUE THREAD

**Issue by ManidharVutla** [ManidharVutla/Stock-Info#1]
Write logic to create:

* Check for the hidden file with name .secret.txt
* If found, fetch the username and password.
* Else ask for user name and password 
* Create a hidden file named .secret.txt
* Fetch the username and password from the secret file.

**Comment by michaeljgallagher** [comment]
I went ahead and implemented this, let me know if you like it. PR #4

**Comment by ManidharVutla** [comment]
It was great, thanks for the help!
